name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: "1.21.5"

#      - name: Run static checks
#        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
#        with:
#          # renovate: datasource=docker depName=golangci/golangci-lint
#          version: v1.55.2
#          args: --config=.golangci.yml --verbose
#          skip-cache: true

      - name: Check go.mod
        run: |
          go mod tidy
          go mod verify
          git status
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy', and submit your changes for go.mod"; exit 1)

      - name: Run unit tests
        run: make test

      - name: Build
        run: make
